Depot Extension Part 1 completed (Migrations)
abhikanojia/depot pull request #1
Opened 2017-12-08 12:15 UTC by abhikanojia

2017-12-08 13:09 UTC, harsh-ag requested changes

2017-12-08 13:09 UTC, harsh-ag commented on depot/db/migrate/20171208102526_add_columns_to_products.rb
> +class AddColumnsToProducts < ActiveRecord::Migration[5.0]
This can be written in a better way which will take less time to execute.

2017-12-08 13:09 UTC, harsh-ag commented on depot/db/migrate/20171208110127_change_default_value_of_enabled.rb
> +class ChangeDefaultValueOfEnabled < ActiveRecord::Migration[5.0]
What will happen in the case of rollback?

2017-12-08 13:09 UTC, harsh-ag commented on depot/config/locales/en.yml
> +  products:
This is not being used.

2017-12-08 13:09 UTC, harsh-ag commented on depot/config/routes.rb
> +    resources :products
Please make sure that the assets are not pushed on GitHub.

2017-12-08 13:09 UTC, harsh-ag commented on depot/app/views/products/_form.html.erb
> +    <%= f.check_box :enabled, checked_value: true, unchecked_value: false %>
no need to mention true and false values here.

2017-12-08 17:54 UTC, abhikanojia commented on depot/db/migrate/20171208102526_add_columns_to_products.rb
> +class AddColumnsToProducts < ActiveRecord::Migration[5.0]
made changes Thnks ! :slightly_smiling_face:

2017-12-08 17:56 UTC, abhikanojia commented on depot/db/migrate/20171208110127_change_default_value_of_enabled.rb
> +class ChangeDefaultValueOfEnabled < ActiveRecord::Migration[5.0]
Thanks for pointing it out .. it will create a IrreversibleMigration exception. I have corrected it too.

2017-12-11 06:56 UTC, harsh-ag approved these changes

2017-12-11 06:57 UTC, merged